<?php
//Generated by buildORM from the cred:Carriers

	

	class CarrierBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Carriers';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function ProviderCarrier_bunch()
        {
                return $this->hasMany('ProviderCarrier',carrier_id);
               // return $this->hasOne('ProviderCarrier',carrier_id);
        }


	}//the end of class Carrier		
?>