<?php
//Generated by buildORM from the cred:Citys

	

	class CityBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Citys';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Address_bunch()
        {
                return $this->hasMany('Address',city_id);
               // return $this->hasOne('Address',city_id);
        }


	}//the end of class City		
?>