<?php
//Generated by buildORM from the cred:Days

	

	class DayBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Days';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Hour_bunch()
        {
                return $this->hasMany('Hour',day_id);
               // return $this->hasOne('Hour',day_id);
        }


	}//the end of class Day		
?>