<?php
//Generated by buildORM from the cred:DocumentTypes

	

	class DocumentTypeBase extends BaseORM{ //which extends Eloquent...

		var $table = 'DocumentTypes';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Document_bunch()
        {
                return $this->hasMany('Document',documenttype_id);
               // return $this->hasOne('Document',documenttype_id);
        }


	}//the end of class DocumentType		
?>