<?php
//Generated by buildORM from the cred:Documents

	

	class DocumentBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Documents';
 

        //autogenerated this function... 
        public function DocumentType()
        {
                return $this->belongs_to('DocumentType','documenttype_id');
        }


        //autogenerated this function... 
        public function DocumentState()
        {
                return $this->belongs_to('DocumentState','documentstate_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


	}//the end of class Document		
?>