<?php
//Generated by buildORM from the cred:EducationLevels

	

	class EducationLevelBase extends BaseORM{ //which extends Eloquent...

		var $table = 'EducationLevels';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

	}//the end of class EducationLevel		
?>