<?php
//Generated by buildORM from the cred:EducationLevels

	

	class EducationLevelBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'EducationLevels';
 

	}//the end of class EducationLevel		
?>