<?php
//Generated by buildORM from the cred:Hoursprofiles

	

	class HoursprofileBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Hoursprofiles';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Hour_bunch()
        {
                return $this->hasMany('Hour',hoursprofile_id);
               // return $this->hasOne('Hour',hoursprofile_id);
        }


        //autogenerated this function... 
        public function Practice_bunch()
        {
                return $this->hasMany('Practice',hoursprofile_id);
               // return $this->hasOne('Practice',hoursprofile_id);
        }


	}//the end of class Hoursprofile		
?>