<?php
//Generated by buildORM from the cred:Hours

	

	class HourBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Hours';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Hoursprofile()
        {
                return $this->belongs_to('Hoursprofile','hoursprofile_id');
        }


        //autogenerated this function... 
        public function Day()
        {
                return $this->belongs_to('Day','day_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


	}//the end of class Hour		
?>