<?php
//Generated by buildORM from the cred:Identifiers

	

	class IdentifierBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Identifiers';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Provider()
        {
                return $this->belongs_to('Provider','provider_id');
        }


        //autogenerated this function... 
        public function IdentifierType()
        {
                return $this->belongs_to('IdentifierType','identifiertype_id');
        }


        //autogenerated this function... 
        public function Issue_State()
        {
                return $this->belongs_to('State','issue_state_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


	}//the end of class Identifier		
?>