<?php
//Generated by buildORM from the cred:IdentifierTypes

	

	class IdentifierTypeBase extends BaseORM{ //which extends Eloquent...

		var $table = 'IdentifierTypes';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Identifier_bunch()
        {
                return $this->hasMany('Identifier',identifiertype_id);
               // return $this->hasOne('Identifier',identifiertype_id);
        }


	}//the end of class IdentifierType		
?>