<?php
//Generated by buildORM from the cred:Languages

	

	class LanguageBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Languages';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Practice_from_interpreters_0_bunch()
        {
                return $this->hasMany('Practice',interpreters_0_practice_id);
               // return $this->hasOne('Practice',interpreters_0_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_interpreters_1_bunch()
        {
                return $this->hasMany('Practice',interpreters_1_practice_id);
               // return $this->hasOne('Practice',interpreters_1_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_interpreters_2_bunch()
        {
                return $this->hasMany('Practice',interpreters_2_practice_id);
               // return $this->hasOne('Practice',interpreters_2_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_interpreters_3_bunch()
        {
                return $this->hasMany('Practice',interpreters_3_practice_id);
               // return $this->hasOne('Practice',interpreters_3_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_interpreters_4_bunch()
        {
                return $this->hasMany('Practice',interpreters_4_practice_id);
               // return $this->hasOne('Practice',interpreters_4_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_Provider_0_bunch()
        {
                return $this->hasMany('Practice',provider_0_practice_id);
               // return $this->hasOne('Practice',provider_0_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_Provider_1_bunch()
        {
                return $this->hasMany('Practice',provider_1_practice_id);
               // return $this->hasOne('Practice',provider_1_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_Provider_2_bunch()
        {
                return $this->hasMany('Practice',provider_2_practice_id);
               // return $this->hasOne('Practice',provider_2_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_Staff_0_bunch()
        {
                return $this->hasMany('Practice',staff_0_practice_id);
               // return $this->hasOne('Practice',staff_0_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_Staff_1_bunch()
        {
                return $this->hasMany('Practice',staff_1_practice_id);
               // return $this->hasOne('Practice',staff_1_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_Staff_2_bunch()
        {
                return $this->hasMany('Practice',staff_2_practice_id);
               // return $this->hasOne('Practice',staff_2_practice_id);
        }


	}//the end of class Language		
?>