<?php
//Generated by buildORM from the cred:laravel_migrations

	

	class laravel_migrationBase extends BaseORM{ //which extends Eloquent...

		var $table = 'laravel_migrations';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

	}//the end of class laravel_migration		
?>