<?php
//Generated by buildORM from the cred:Malpracticeawards

	

	class MalpracticeawardBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Malpracticeawards';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Insurancecoverage()
        {
                return $this->belongs_to('Insurancecoverage','insurancecoverage_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


	}//the end of class Malpracticeaward		
?>