<?php
//Generated by buildORM from the cred:Nonphysicians

	

	class NonphysicianBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Nonphysicians';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function State()
        {
                return $this->belongs_to('State','state_id');
        }


        //autogenerated this function... 
        public function Practice_from_a_0_bunch()
        {
                return $this->hasMany('Practice',a_0_practice_id);
               // return $this->hasOne('Practice',a_0_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_a_1_bunch()
        {
                return $this->hasMany('Practice',a_1_practice_id);
               // return $this->hasOne('Practice',a_1_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_a_2_bunch()
        {
                return $this->hasMany('Practice',a_2_practice_id);
               // return $this->hasOne('Practice',a_2_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_a_3_bunch()
        {
                return $this->hasMany('Practice',a_3_practice_id);
               // return $this->hasOne('Practice',a_3_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_a_4_bunch()
        {
                return $this->hasMany('Practice',a_4_practice_id);
               // return $this->hasOne('Practice',a_4_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_a_5_bunch()
        {
                return $this->hasMany('Practice',a_5_practice_id);
               // return $this->hasOne('Practice',a_5_practice_id);
        }


	}//the end of class Nonphysician		
?>