<?php
//Generated by buildORM from the cred:Notetypes

	

	class NotetypeBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Notetypes';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Note_bunch()
        {
                return $this->hasMany('Note',notetype_id);
               // return $this->hasOne('Note',notetype_id);
        }


	}//the end of class Notetype		
?>