<?php
//Generated by buildORM from the cred:Notes

	

	class NoteBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Notes';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function row()
        {
                return $this->belongs_to('row','row_id');
        }


        //autogenerated this function... 
        public function User()
        {
                return $this->belongs_to('User','user_id');
        }


	}//the end of class Note		
?>