<?php
//Generated by buildORM from the cred:Phones

	

	class PhoneBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Phones';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function EducationInstitution_bunch()
        {
                return $this->hasMany('EducationInstitution',phone_id);
               // return $this->hasOne('EducationInstitution',phone_id);
        }


        //autogenerated this function... 
        public function Hospital_bunch()
        {
                return $this->hasMany('Hospital',phone_id);
               // return $this->hasOne('Hospital',phone_id);
        }


        //autogenerated this function... 
        public function Medicalboard_bunch()
        {
                return $this->hasMany('Medicalboard',phone_id);
               // return $this->hasOne('Medicalboard',phone_id);
        }


        //autogenerated this function... 
        public function Provider_from_Home_bunch()
        {
                return $this->hasMany('Provider',home_provider_id);
               // return $this->hasOne('Provider',home_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_bunch()
        {
                return $this->hasMany('Provider',corr_provider_id);
               // return $this->hasOne('Provider',corr_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_Fax_bunch()
        {
                return $this->hasMany('Provider',corr_fax_provider_id);
               // return $this->hasOne('Provider',corr_fax_provider_id);
        }


	}//the end of class Phone		
?>