<?php
//Generated by buildORM from the cred:Phones

	

	class PhoneBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Phones';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Billingcompany_bunch()
        {
                return $this->hasMany('Billingcompany',phone_id);
               // return $this->hasOne('Billingcompany',phone_id);
        }


        //autogenerated this function... 
        public function Billingcompany_from_Fax_bunch()
        {
                return $this->hasMany('Billingcompany',fax_billingcompany_id);
               // return $this->hasOne('Billingcompany',fax_billingcompany_id);
        }


        //autogenerated this function... 
        public function CredentialOrganization_bunch()
        {
                return $this->hasMany('CredentialOrganization',phone_id);
               // return $this->hasOne('CredentialOrganization',phone_id);
        }


        //autogenerated this function... 
        public function CredentialOrganization_from_Fax_bunch()
        {
                return $this->hasMany('CredentialOrganization',fax_credentialorganization_id);
               // return $this->hasOne('CredentialOrganization',fax_credentialorganization_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_bunch()
        {
                return $this->hasMany('EducationInstitution',phone_id);
               // return $this->hasOne('EducationInstitution',phone_id);
        }


        //autogenerated this function... 
        public function Hospital_bunch()
        {
                return $this->hasMany('Hospital',phone_id);
               // return $this->hasOne('Hospital',phone_id);
        }


        //autogenerated this function... 
        public function Insurancecarrier_bunch()
        {
                return $this->hasMany('Insurancecarrier',phone_id);
               // return $this->hasOne('Insurancecarrier',phone_id);
        }


        //autogenerated this function... 
        public function Insurancecarrier_from_Fax_bunch()
        {
                return $this->hasMany('Insurancecarrier',fax_insurancecarrier_id);
               // return $this->hasOne('Insurancecarrier',fax_insurancecarrier_id);
        }


        //autogenerated this function... 
        public function Medicalboard_bunch()
        {
                return $this->hasMany('Medicalboard',phone_id);
               // return $this->hasOne('Medicalboard',phone_id);
        }


        //autogenerated this function... 
        public function Medicalboard_from_Fax_bunch()
        {
                return $this->hasMany('Medicalboard',fax_medicalboard_id);
               // return $this->hasOne('Medicalboard',fax_medicalboard_id);
        }


        //autogenerated this function... 
        public function Practice_from_office_manager_or_contact_fax_bunch()
        {
                return $this->hasMany('Practice',office_manager_or_contact_fax_practice_id);
               // return $this->hasOne('Practice',office_manager_or_contact_fax_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_office_manager_or_cantact_bunch()
        {
                return $this->hasMany('Practice',office_manager_or_cantact_practice_id);
               // return $this->hasOne('Practice',office_manager_or_cantact_practice_id);
        }


        //autogenerated this function... 
        public function Practice_bunch()
        {
                return $this->hasMany('Practice',phone_id);
               // return $this->hasOne('Practice',phone_id);
        }


        //autogenerated this function... 
        public function Practice_from_Fax_bunch()
        {
                return $this->hasMany('Practice',fax_practice_id);
               // return $this->hasOne('Practice',fax_practice_id);
        }


        //autogenerated this function... 
        public function Provider_from_Home_bunch()
        {
                return $this->hasMany('Provider',home_provider_id);
               // return $this->hasOne('Provider',home_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_bunch()
        {
                return $this->hasMany('Provider',corr_provider_id);
               // return $this->hasOne('Provider',corr_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_Fax_bunch()
        {
                return $this->hasMany('Provider',corr_fax_provider_id);
               // return $this->hasOne('Provider',corr_fax_provider_id);
        }


	}//the end of class Phone		
?>