<?php
//Generated by buildORM from the cred:Practices

	

	class PracticeBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Practices';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Servicecode()
        {
                return $this->belongs_to('Servicecode','servicecode_id');
        }


        //autogenerated this function... 
        public function interpreters_0_Language()
        {
                return $this->belongs_to('Language','interpreters_0_language_id');
        }


        //autogenerated this function... 
        public function interpreters_1_Language()
        {
                return $this->belongs_to('Language','interpreters_1_language_id');
        }


        //autogenerated this function... 
        public function interpreters_2_Language()
        {
                return $this->belongs_to('Language','interpreters_2_language_id');
        }


        //autogenerated this function... 
        public function interpreters_3_Language()
        {
                return $this->belongs_to('Language','interpreters_3_language_id');
        }


        //autogenerated this function... 
        public function interpreters_4_Language()
        {
                return $this->belongs_to('Language','interpreters_4_language_id');
        }


        //autogenerated this function... 
        public function non_physician_0_Provider()
        {
                return $this->belongs_to('Provider','non_physician_0_provider_id');
        }


        //autogenerated this function... 
        public function non_physician_1_Provider()
        {
                return $this->belongs_to('Provider','non_physician_1_provider_id');
        }


        //autogenerated this function... 
        public function non_physician_2_Provider()
        {
                return $this->belongs_to('Provider','non_physician_2_provider_id');
        }


        //autogenerated this function... 
        public function non_physician_3_Provider()
        {
                return $this->belongs_to('Provider','non_physician_3_provider_id');
        }


        //autogenerated this function... 
        public function non_physician_4_Provider()
        {
                return $this->belongs_to('Provider','non_physician_4_provider_id');
        }


        //autogenerated this function... 
        public function non_physician_5_Provider()
        {
                return $this->belongs_to('Provider','non_physician_5_provider_id');
        }


        //autogenerated this function... 
        public function office_manager_or_contact_fax_Phone()
        {
                return $this->belongs_to('Phone','office_manager_or_contact_fax_phone_id');
        }


        //autogenerated this function... 
        public function office_manager_or_cantact_Phone()
        {
                return $this->belongs_to('Phone','office_manager_or_cantact_phone_id');
        }


        //autogenerated this function... 
        public function Provider_0_Language()
        {
                return $this->belongs_to('Language','provider_0_language_id');
        }


        //autogenerated this function... 
        public function Provider_1_Language()
        {
                return $this->belongs_to('Language','provider_1_language_id');
        }


        //autogenerated this function... 
        public function Provider_2_Language()
        {
                return $this->belongs_to('Language','provider_2_language_id');
        }


        //autogenerated this function... 
        public function Staff_0_Language()
        {
                return $this->belongs_to('Language','staff_0_language_id');
        }


        //autogenerated this function... 
        public function Staff_1_Language()
        {
                return $this->belongs_to('Language','staff_1_language_id');
        }


        //autogenerated this function... 
        public function Staff_2_Language()
        {
                return $this->belongs_to('Language','staff_2_language_id');
        }


        //autogenerated this function... 
        public function Phone()
        {
                return $this->belongs_to('Phone','phone_id');
        }


        //autogenerated this function... 
        public function Fax_Phone()
        {
                return $this->belongs_to('Phone','fax_phone_id');
        }


        //autogenerated this function... 
        public function Billingcompany()
        {
                return $this->belongs_to('Billingcompany','billingcompany_id');
        }


        //autogenerated this function... 
        public function Address()
        {
                return $this->belongs_to('Address','address_id');
        }


        //autogenerated this function... 
        public function CredentialOrganization()
        {
                return $this->belongs_to('CredentialOrganization','credentialorganization_id');
        }


        //autogenerated this function... 
        public function Hoursprofile()
        {
                return $this->belongs_to('Hoursprofile','hoursprofile_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function ProviderPractice_bunch()
        {
                return $this->hasMany('ProviderPractice',practice_id);
               // return $this->hasOne('ProviderPractice',practice_id);
        }


	}//the end of class Practice		
?>