<?php
//Generated by buildORM from the cred:ProviderSpecialitys

	

	class ProviderSpecialityBase extends BaseORM{ //which extends Eloquent...

		var $table = 'ProviderSpecialitys';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Provider()
        {
                return $this->belongs_to('Provider','provider_id');
        }


        //autogenerated this function... 
        public function Speciality()
        {
                return $this->belongs_to('Speciality','speciality_id');
        }


        //autogenerated this function... 
        public function Medicalboard()
        {
                return $this->belongs_to('Medicalboard','medicalboard_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function ProviderEducation_bunch()
        {
                return $this->hasMany('ProviderEducation',providerspeciality_id);
               // return $this->hasOne('ProviderEducation',providerspeciality_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_bunch()
        {
                return $this->hasMany('ProviderLicense',providerspeciality_id);
               // return $this->hasOne('ProviderLicense',providerspeciality_id);
        }


        //autogenerated this function... 
        public function ProvidersProviderSpeciality_bunch()
        {
                return $this->hasMany('ProvidersProviderSpeciality',providerspeciality_id);
               // return $this->hasOne('ProvidersProviderSpeciality',providerspeciality_id);
        }


	}//the end of class ProviderSpeciality		
?>