<?php
//Generated by buildORM from the cred:Providers

	

	class ProviderBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Providers';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function ProviderStatus()
        {
                return $this->belongs_to('ProviderStatus','providerstatus_id');
        }


        //autogenerated this function... 
        public function Birth_Address()
        {
                return $this->belongs_to('Address','birth_address_id');
        }


        //autogenerated this function... 
        public function Gender()
        {
                return $this->belongs_to('Gender','gender_id');
        }


        //autogenerated this function... 
        public function Home_Phone()
        {
                return $this->belongs_to('Phone','home_phone_id');
        }


        //autogenerated this function... 
        public function Home_Address()
        {
                return $this->belongs_to('Address','home_address_id');
        }


        //autogenerated this function... 
        public function Corr_Phone()
        {
                return $this->belongs_to('Phone','corr_phone_id');
        }


        //autogenerated this function... 
        public function Corr_Address()
        {
                return $this->belongs_to('Address','corr_address_id');
        }


        //autogenerated this function... 
        public function Corr_Fax_Phone()
        {
                return $this->belongs_to('Phone','corr_fax_phone_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Document_bunch()
        {
                return $this->hasMany('Document',provider_id);
               // return $this->hasOne('Document',provider_id);
        }


        //autogenerated this function... 
        public function Note_bunch()
        {
                return $this->hasMany('Note',provider_id);
               // return $this->hasOne('Note',provider_id);
        }


        //autogenerated this function... 
        public function ProviderCarrier_bunch()
        {
                return $this->hasMany('ProviderCarrier',provider_id);
               // return $this->hasOne('ProviderCarrier',provider_id);
        }


        //autogenerated this function... 
        public function ProviderCoverage_bunch()
        {
                return $this->hasMany('ProviderCoverage',provider_id);
               // return $this->hasOne('ProviderCoverage',provider_id);
        }


        //autogenerated this function... 
        public function ProviderCredential_bunch()
        {
                return $this->hasMany('ProviderCredential',provider_id);
               // return $this->hasOne('ProviderCredential',provider_id);
        }


        //autogenerated this function... 
        public function ProviderEducation_bunch()
        {
                return $this->hasMany('ProviderEducation',provider_id);
               // return $this->hasOne('ProviderEducation',provider_id);
        }


        //autogenerated this function... 
        public function ProviderHospital_bunch()
        {
                return $this->hasMany('ProviderHospital',provider_id);
               // return $this->hasOne('ProviderHospital',provider_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_bunch()
        {
                return $this->hasMany('ProviderLicense',provider_id);
               // return $this->hasOne('ProviderLicense',provider_id);
        }


        //autogenerated this function... 
        public function ProviderNetwork_bunch()
        {
                return $this->hasMany('ProviderNetwork',provider_id);
               // return $this->hasOne('ProviderNetwork',provider_id);
        }


        //autogenerated this function... 
        public function ProviderReference_bunch()
        {
                return $this->hasMany('ProviderReference',provider_id);
               // return $this->hasOne('ProviderReference',provider_id);
        }


        //autogenerated this function... 
        public function ProviderSpeciality_bunch()
        {
                return $this->hasMany('ProviderSpeciality',provider_id);
               // return $this->hasOne('ProviderSpeciality',provider_id);
        }


        //autogenerated this function... 
        public function ProvidersProviderSpeciality_bunch()
        {
                return $this->hasMany('ProvidersProviderSpeciality',provider_id);
               // return $this->hasOne('ProvidersProviderSpeciality',provider_id);
        }


	}//the end of class Provider		
?>