<?php
//Generated by buildORM from the cred:ProvidersProviderSpecialitys

	

	class ProvidersProviderSpecialityBase extends BaseORM{ //which extends Eloquent...

		var $table = 'ProvidersProviderSpecialitys';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function ProviderSpeciality()
        {
                return $this->belongs_to('ProviderSpeciality','providerspeciality_id');
        }


        //autogenerated this function... 
        public function Provider()
        {
                return $this->belongs_to('Provider','provider_id');
        }


	}//the end of class ProvidersProviderSpeciality		
?>