<?php
//Generated by buildORM from the cred:ProviderStates

	

	class ProviderStateBase extends BaseORM{ //which extends Eloquent...

		var $table = 'ProviderStates';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Provider_bunch()
        {
                return $this->hasMany('Provider',providerstate_id);
               // return $this->hasOne('Provider',providerstate_id);
        }


	}//the end of class ProviderState		
?>