<?php
//Generated by buildORM from the cred:ProviderEducationsProviderEducations

	

	class ProviderEducationsProviderEducationBase extends BaseORM{ //which extends Eloquent...

		var $table = 'ProviderEducationsProviderEducations';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function ProviderEducation()
        {
                return $this->belongs_to('ProviderEducation','providereducation_id');
        }


	}//the end of class ProviderEducationsProviderEducation		
?>