<?php
//Generated by buildORM from the cred:Providers

	

	class ProviderBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Providers';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function ProviderState()
        {
                return $this->belongs_to('ProviderState','providerstate_id');
        }


        //autogenerated this function... 
        public function Birth_Address()
        {
                return $this->belongs_to('Address','birth_address_id');
        }


        //autogenerated this function... 
        public function Gender()
        {
                return $this->belongs_to('Gender','gender_id');
        }


        //autogenerated this function... 
        public function Home_Phone()
        {
                return $this->belongs_to('Phone','home_phone_id');
        }


        //autogenerated this function... 
        public function Home_Address()
        {
                return $this->belongs_to('Address','home_address_id');
        }


        //autogenerated this function... 
        public function Corr_Phone()
        {
                return $this->belongs_to('Phone','corr_phone_id');
        }


        //autogenerated this function... 
        public function Corr_Address()
        {
                return $this->belongs_to('Address','corr_address_id');
        }


        //autogenerated this function... 
        public function Corr_Fax_Phone()
        {
                return $this->belongs_to('Phone','corr_fax_phone_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Document_bunch()
        {
                return $this->hasMany('Document',provider_id);
               // return $this->hasOne('Document',provider_id);
        }


        //autogenerated this function... 
        public function Identifier_bunch()
        {
                return $this->hasMany('Identifier',provider_id);
               // return $this->hasOne('Identifier',provider_id);
        }


        //autogenerated this function... 
        public function Insurancecoverage_bunch()
        {
                return $this->hasMany('Insurancecoverage',provider_id);
               // return $this->hasOne('Insurancecoverage',provider_id);
        }


        //autogenerated this function... 
        public function Note_bunch()
        {
                return $this->hasMany('Note',provider_id);
               // return $this->hasOne('Note',provider_id);
        }


        //autogenerated this function... 
        public function Practice_from_non_physician_0_bunch()
        {
                return $this->hasMany('Practice',non_physician_0_practice_id);
               // return $this->hasOne('Practice',non_physician_0_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_non_physician_1_bunch()
        {
                return $this->hasMany('Practice',non_physician_1_practice_id);
               // return $this->hasOne('Practice',non_physician_1_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_non_physician_2_bunch()
        {
                return $this->hasMany('Practice',non_physician_2_practice_id);
               // return $this->hasOne('Practice',non_physician_2_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_non_physician_3_bunch()
        {
                return $this->hasMany('Practice',non_physician_3_practice_id);
               // return $this->hasOne('Practice',non_physician_3_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_non_physician_4_bunch()
        {
                return $this->hasMany('Practice',non_physician_4_practice_id);
               // return $this->hasOne('Practice',non_physician_4_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_non_physician_5_bunch()
        {
                return $this->hasMany('Practice',non_physician_5_practice_id);
               // return $this->hasOne('Practice',non_physician_5_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_NonPhysician_0_bunch()
        {
                return $this->hasMany('Practice',nonphysician_0_practice_id);
               // return $this->hasOne('Practice',nonphysician_0_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_NonPhysician_1_bunch()
        {
                return $this->hasMany('Practice',nonphysician_1_practice_id);
               // return $this->hasOne('Practice',nonphysician_1_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_NonPhysician_2_bunch()
        {
                return $this->hasMany('Practice',nonphysician_2_practice_id);
               // return $this->hasOne('Practice',nonphysician_2_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_NonPhysician_3_bunch()
        {
                return $this->hasMany('Practice',nonphysician_3_practice_id);
               // return $this->hasOne('Practice',nonphysician_3_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_NonPhysician_4_bunch()
        {
                return $this->hasMany('Practice',nonphysician_4_practice_id);
               // return $this->hasOne('Practice',nonphysician_4_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_NonPhysician_5_bunch()
        {
                return $this->hasMany('Practice',nonphysician_5_practice_id);
               // return $this->hasOne('Practice',nonphysician_5_practice_id);
        }


        //autogenerated this function... 
        public function ProviderCallcoverage_bunch()
        {
                return $this->hasMany('ProviderCallcoverage',provider_id);
               // return $this->hasOne('ProviderCallcoverage',provider_id);
        }


        //autogenerated this function... 
        public function ProviderCallcoverage_from_CallCoverage_bunch()
        {
                return $this->hasMany('ProviderCallcoverage',callcoverage_providercallcoverage_id);
               // return $this->hasOne('ProviderCallcoverage',callcoverage_providercallcoverage_id);
        }


        //autogenerated this function... 
        public function ProviderCarrier_bunch()
        {
                return $this->hasMany('ProviderCarrier',provider_id);
               // return $this->hasOne('ProviderCarrier',provider_id);
        }


        //autogenerated this function... 
        public function ProviderCredential_bunch()
        {
                return $this->hasMany('ProviderCredential',provider_id);
               // return $this->hasOne('ProviderCredential',provider_id);
        }


        //autogenerated this function... 
        public function ProviderEducation_bunch()
        {
                return $this->hasMany('ProviderEducation',provider_id);
               // return $this->hasOne('ProviderEducation',provider_id);
        }


        //autogenerated this function... 
        public function ProviderHospital_bunch()
        {
                return $this->hasMany('ProviderHospital',provider_id);
               // return $this->hasOne('ProviderHospital',provider_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_bunch()
        {
                return $this->hasMany('ProviderLicense',provider_id);
               // return $this->hasOne('ProviderLicense',provider_id);
        }


        //autogenerated this function... 
        public function ProviderNetwork_bunch()
        {
                return $this->hasMany('ProviderNetwork',provider_id);
               // return $this->hasOne('ProviderNetwork',provider_id);
        }


        //autogenerated this function... 
        public function ProviderPartner_bunch()
        {
                return $this->hasMany('ProviderPartner',provider_id);
               // return $this->hasOne('ProviderPartner',provider_id);
        }


        //autogenerated this function... 
        public function ProviderPartner_from_Partner_bunch()
        {
                return $this->hasMany('ProviderPartner',partner_providerpartner_id);
               // return $this->hasOne('ProviderPartner',partner_providerpartner_id);
        }


        //autogenerated this function... 
        public function ProviderPractice_bunch()
        {
                return $this->hasMany('ProviderPractice',provider_id);
               // return $this->hasOne('ProviderPractice',provider_id);
        }


        //autogenerated this function... 
        public function ProviderReference_bunch()
        {
                return $this->hasMany('ProviderReference',provider_id);
               // return $this->hasOne('ProviderReference',provider_id);
        }


        //autogenerated this function... 
        public function ProviderReference_from_Reference_bunch()
        {
                return $this->hasMany('ProviderReference',reference_providerreference_id);
               // return $this->hasOne('ProviderReference',reference_providerreference_id);
        }


        //autogenerated this function... 
        public function ProviderSpeciality_bunch()
        {
                return $this->hasMany('ProviderSpeciality',provider_id);
               // return $this->hasOne('ProviderSpeciality',provider_id);
        }


        //autogenerated this function... 
        public function ProvidersProviderSpeciality_bunch()
        {
                return $this->hasMany('ProvidersProviderSpeciality',provider_id);
               // return $this->hasOne('ProvidersProviderSpeciality',provider_id);
        }


	}//the end of class Provider		
?>