<?php
//Generated by buildORM from the cred:rows

	

	class rowBase extends BaseORM{ //which extends Eloquent...

		var $table = 'rows';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Note_bunch()
        {
                return $this->hasMany('Note',row_id);
               // return $this->hasOne('Note',row_id);
        }


        //autogenerated this function... 
        public function TagLink_bunch()
        {
                return $this->hasMany('TagLink',row_id);
               // return $this->hasOne('TagLink',row_id);
        }


	}//the end of class row		
?>