<?php
//Generated by buildORM from the cred:TagLinks

	

	class TagLinkBase extends BaseORM{ //which extends Eloquent...

		var $table = 'TagLinks';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function row()
        {
                return $this->belongs_to('row','row_id');
        }


        //autogenerated this function... 
        public function Tag()
        {
                return $this->belongs_to('Tag','tag_id');
        }


        //autogenerated this function... 
        public function User()
        {
                return $this->belongs_to('User','user_id');
        }


	}//the end of class TagLink		
?>