<?php
//Generated by buildORM from the cred:taxonomys

	

	class taxonomyBase extends BaseORM{ //which extends Eloquent...

		var $table = 'taxonomys';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

	}//the end of class taxonomy		
?>