<?php
//Generated by buildORM from the cred:Tests

	

	class TestBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Tests';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

	}//the end of class Test		
?>