<?php
//Generated by buildORM from the cred:Users

	

	class UserBase extends BaseORM{ //which extends Eloquent...

		var $table = 'Users';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

        //autogenerated this function... 
        public function Address_from_created_by_bunch()
        {
                return $this->hasMany('Address',created_by_address_id);
               // return $this->hasOne('Address',created_by_address_id);
        }


        //autogenerated this function... 
        public function Address_from_modified_by_bunch()
        {
                return $this->hasMany('Address',modified_by_address_id);
               // return $this->hasOne('Address',modified_by_address_id);
        }


        //autogenerated this function... 
        public function Billingcompany_from_created_by_bunch()
        {
                return $this->hasMany('Billingcompany',created_by_billingcompany_id);
               // return $this->hasOne('Billingcompany',created_by_billingcompany_id);
        }


        //autogenerated this function... 
        public function Billingcompany_from_modified_by_bunch()
        {
                return $this->hasMany('Billingcompany',modified_by_billingcompany_id);
               // return $this->hasOne('Billingcompany',modified_by_billingcompany_id);
        }


        //autogenerated this function... 
        public function City_from_created_by_bunch()
        {
                return $this->hasMany('City',created_by_city_id);
               // return $this->hasOne('City',created_by_city_id);
        }


        //autogenerated this function... 
        public function City_from_modified_by_bunch()
        {
                return $this->hasMany('City',modified_by_city_id);
               // return $this->hasOne('City',modified_by_city_id);
        }


        //autogenerated this function... 
        public function Country_from_created_by_bunch()
        {
                return $this->hasMany('Country',created_by_country_id);
               // return $this->hasOne('Country',created_by_country_id);
        }


        //autogenerated this function... 
        public function Country_from_modified_by_bunch()
        {
                return $this->hasMany('Country',modified_by_country_id);
               // return $this->hasOne('Country',modified_by_country_id);
        }


        //autogenerated this function... 
        public function County_from_created_by_bunch()
        {
                return $this->hasMany('County',created_by_county_id);
               // return $this->hasOne('County',created_by_county_id);
        }


        //autogenerated this function... 
        public function County_from_modified_by_bunch()
        {
                return $this->hasMany('County',modified_by_county_id);
               // return $this->hasOne('County',modified_by_county_id);
        }


        //autogenerated this function... 
        public function CredentialOrganization_from_created_by_bunch()
        {
                return $this->hasMany('CredentialOrganization',created_by_credentialorganization_id);
               // return $this->hasOne('CredentialOrganization',created_by_credentialorganization_id);
        }


        //autogenerated this function... 
        public function CredentialOrganization_from_modified_by_bunch()
        {
                return $this->hasMany('CredentialOrganization',modified_by_credentialorganization_id);
               // return $this->hasOne('CredentialOrganization',modified_by_credentialorganization_id);
        }


        //autogenerated this function... 
        public function DocumentState_from_created_by_bunch()
        {
                return $this->hasMany('DocumentState',created_by_documentstate_id);
               // return $this->hasOne('DocumentState',created_by_documentstate_id);
        }


        //autogenerated this function... 
        public function DocumentState_from_modified_by_bunch()
        {
                return $this->hasMany('DocumentState',modified_by_documentstate_id);
               // return $this->hasOne('DocumentState',modified_by_documentstate_id);
        }


        //autogenerated this function... 
        public function DocumentType_from_created_by_bunch()
        {
                return $this->hasMany('DocumentType',created_by_documenttype_id);
               // return $this->hasOne('DocumentType',created_by_documenttype_id);
        }


        //autogenerated this function... 
        public function DocumentType_from_modified_by_bunch()
        {
                return $this->hasMany('DocumentType',modified_by_documenttype_id);
               // return $this->hasOne('DocumentType',modified_by_documenttype_id);
        }


        //autogenerated this function... 
        public function Document_from_created_by_bunch()
        {
                return $this->hasMany('Document',created_by_document_id);
               // return $this->hasOne('Document',created_by_document_id);
        }


        //autogenerated this function... 
        public function Document_from_modified_by_bunch()
        {
                return $this->hasMany('Document',modified_by_document_id);
               // return $this->hasOne('Document',modified_by_document_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_from_created_by_bunch()
        {
                return $this->hasMany('EducationInstitution',created_by_educationinstitution_id);
               // return $this->hasOne('EducationInstitution',created_by_educationinstitution_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_from_modified_by_bunch()
        {
                return $this->hasMany('EducationInstitution',modified_by_educationinstitution_id);
               // return $this->hasOne('EducationInstitution',modified_by_educationinstitution_id);
        }


        //autogenerated this function... 
        public function Ethniccode_from_created_by_bunch()
        {
                return $this->hasMany('Ethniccode',created_by_ethniccode_id);
               // return $this->hasOne('Ethniccode',created_by_ethniccode_id);
        }


        //autogenerated this function... 
        public function Ethniccode_from_modified_by_bunch()
        {
                return $this->hasMany('Ethniccode',modified_by_ethniccode_id);
               // return $this->hasOne('Ethniccode',modified_by_ethniccode_id);
        }


        //autogenerated this function... 
        public function Gender_from_created_by_bunch()
        {
                return $this->hasMany('Gender',created_by_gender_id);
               // return $this->hasOne('Gender',created_by_gender_id);
        }


        //autogenerated this function... 
        public function Gender_from_modified_by_bunch()
        {
                return $this->hasMany('Gender',modified_by_gender_id);
               // return $this->hasOne('Gender',modified_by_gender_id);
        }


        //autogenerated this function... 
        public function Hospital_from_created_by_bunch()
        {
                return $this->hasMany('Hospital',created_by_hospital_id);
               // return $this->hasOne('Hospital',created_by_hospital_id);
        }


        //autogenerated this function... 
        public function Hospital_from_modified_by_bunch()
        {
                return $this->hasMany('Hospital',modified_by_hospital_id);
               // return $this->hasOne('Hospital',modified_by_hospital_id);
        }


        //autogenerated this function... 
        public function Hour_from_created_by_bunch()
        {
                return $this->hasMany('Hour',created_by_hour_id);
               // return $this->hasOne('Hour',created_by_hour_id);
        }


        //autogenerated this function... 
        public function Hour_from_modified_by_bunch()
        {
                return $this->hasMany('Hour',modified_by_hour_id);
               // return $this->hasOne('Hour',modified_by_hour_id);
        }


        //autogenerated this function... 
        public function Hoursprofile_from_created_by_bunch()
        {
                return $this->hasMany('Hoursprofile',created_by_hoursprofile_id);
               // return $this->hasOne('Hoursprofile',created_by_hoursprofile_id);
        }


        //autogenerated this function... 
        public function Hoursprofile_from_modified_by_bunch()
        {
                return $this->hasMany('Hoursprofile',modified_by_hoursprofile_id);
               // return $this->hasOne('Hoursprofile',modified_by_hoursprofile_id);
        }


        //autogenerated this function... 
        public function Identifier_from_created_by_bunch()
        {
                return $this->hasMany('Identifier',created_by_identifier_id);
               // return $this->hasOne('Identifier',created_by_identifier_id);
        }


        //autogenerated this function... 
        public function Identifier_from_modified_by_bunch()
        {
                return $this->hasMany('Identifier',modified_by_identifier_id);
               // return $this->hasOne('Identifier',modified_by_identifier_id);
        }


        //autogenerated this function... 
        public function Insurancecarrier_from_created_by_bunch()
        {
                return $this->hasMany('Insurancecarrier',created_by_insurancecarrier_id);
               // return $this->hasOne('Insurancecarrier',created_by_insurancecarrier_id);
        }


        //autogenerated this function... 
        public function Insurancecarrier_from_modified_by_bunch()
        {
                return $this->hasMany('Insurancecarrier',modified_by_insurancecarrier_id);
               // return $this->hasOne('Insurancecarrier',modified_by_insurancecarrier_id);
        }


        //autogenerated this function... 
        public function Insurancecoverage_from_created_by_bunch()
        {
                return $this->hasMany('Insurancecoverage',created_by_insurancecoverage_id);
               // return $this->hasOne('Insurancecoverage',created_by_insurancecoverage_id);
        }


        //autogenerated this function... 
        public function Insurancecoverage_from_modified_by_bunch()
        {
                return $this->hasMany('Insurancecoverage',modified_by_insurancecoverage_id);
               // return $this->hasOne('Insurancecoverage',modified_by_insurancecoverage_id);
        }


        //autogenerated this function... 
        public function Language_from_created_by_bunch()
        {
                return $this->hasMany('Language',created_by_language_id);
               // return $this->hasOne('Language',created_by_language_id);
        }


        //autogenerated this function... 
        public function Language_from_modified_by_bunch()
        {
                return $this->hasMany('Language',modified_by_language_id);
               // return $this->hasOne('Language',modified_by_language_id);
        }


        //autogenerated this function... 
        public function Licensecode_from_created_by_bunch()
        {
                return $this->hasMany('Licensecode',created_by_licensecode_id);
               // return $this->hasOne('Licensecode',created_by_licensecode_id);
        }


        //autogenerated this function... 
        public function Licensecode_from_modified_by_bunch()
        {
                return $this->hasMany('Licensecode',modified_by_licensecode_id);
               // return $this->hasOne('Licensecode',modified_by_licensecode_id);
        }


        //autogenerated this function... 
        public function Malpracticeaward_from_created_by_bunch()
        {
                return $this->hasMany('Malpracticeaward',created_by_malpracticeaward_id);
               // return $this->hasOne('Malpracticeaward',created_by_malpracticeaward_id);
        }


        //autogenerated this function... 
        public function Malpracticeaward_from_modified_by_bunch()
        {
                return $this->hasMany('Malpracticeaward',modified_by_malpracticeaward_id);
               // return $this->hasOne('Malpracticeaward',modified_by_malpracticeaward_id);
        }


        //autogenerated this function... 
        public function Medicalboard_from_created_by_bunch()
        {
                return $this->hasMany('Medicalboard',created_by_medicalboard_id);
               // return $this->hasOne('Medicalboard',created_by_medicalboard_id);
        }


        //autogenerated this function... 
        public function Medicalboard_from_modified_by_bunch()
        {
                return $this->hasMany('Medicalboard',modified_by_medicalboard_id);
               // return $this->hasOne('Medicalboard',modified_by_medicalboard_id);
        }


        //autogenerated this function... 
        public function Network_from_created_by_bunch()
        {
                return $this->hasMany('Network',created_by_network_id);
               // return $this->hasOne('Network',created_by_network_id);
        }


        //autogenerated this function... 
        public function Network_from_modified_by_bunch()
        {
                return $this->hasMany('Network',modified_by_network_id);
               // return $this->hasOne('Network',modified_by_network_id);
        }


        //autogenerated this function... 
        public function Note_from_created_by_bunch()
        {
                return $this->hasMany('Note',created_by_note_id);
               // return $this->hasOne('Note',created_by_note_id);
        }


        //autogenerated this function... 
        public function Note_from_modified_by_bunch()
        {
                return $this->hasMany('Note',modified_by_note_id);
               // return $this->hasOne('Note',modified_by_note_id);
        }


        //autogenerated this function... 
        public function Panel_from_created_by_bunch()
        {
                return $this->hasMany('Panel',created_by_panel_id);
               // return $this->hasOne('Panel',created_by_panel_id);
        }


        //autogenerated this function... 
        public function Panel_from_modified_by_bunch()
        {
                return $this->hasMany('Panel',modified_by_panel_id);
               // return $this->hasOne('Panel',modified_by_panel_id);
        }


        //autogenerated this function... 
        public function Patientacceptcode_from_created_by_bunch()
        {
                return $this->hasMany('Patientacceptcode',created_by_patientacceptcode_id);
               // return $this->hasOne('Patientacceptcode',created_by_patientacceptcode_id);
        }


        //autogenerated this function... 
        public function Patientacceptcode_from_modified_by_bunch()
        {
                return $this->hasMany('Patientacceptcode',modified_by_patientacceptcode_id);
               // return $this->hasOne('Patientacceptcode',modified_by_patientacceptcode_id);
        }


        //autogenerated this function... 
        public function Phonecoveragecode_from_created_by_bunch()
        {
                return $this->hasMany('Phonecoveragecode',created_by_phonecoveragecode_id);
               // return $this->hasOne('Phonecoveragecode',created_by_phonecoveragecode_id);
        }


        //autogenerated this function... 
        public function Phonecoveragecode_from_modified_by_bunch()
        {
                return $this->hasMany('Phonecoveragecode',modified_by_phonecoveragecode_id);
               // return $this->hasOne('Phonecoveragecode',modified_by_phonecoveragecode_id);
        }


        //autogenerated this function... 
        public function Phone_from_created_by_bunch()
        {
                return $this->hasMany('Phone',created_by_phone_id);
               // return $this->hasOne('Phone',created_by_phone_id);
        }


        //autogenerated this function... 
        public function Phone_from_modified_by_bunch()
        {
                return $this->hasMany('Phone',modified_by_phone_id);
               // return $this->hasOne('Phone',modified_by_phone_id);
        }


        //autogenerated this function... 
        public function Practice_from_created_by_bunch()
        {
                return $this->hasMany('Practice',created_by_practice_id);
               // return $this->hasOne('Practice',created_by_practice_id);
        }


        //autogenerated this function... 
        public function Practice_from_modified_by_bunch()
        {
                return $this->hasMany('Practice',modified_by_practice_id);
               // return $this->hasOne('Practice',modified_by_practice_id);
        }


        //autogenerated this function... 
        public function Privilege_from_created_by_bunch()
        {
                return $this->hasMany('Privilege',created_by_privilege_id);
               // return $this->hasOne('Privilege',created_by_privilege_id);
        }


        //autogenerated this function... 
        public function Privilege_from_modified_by_bunch()
        {
                return $this->hasMany('Privilege',modified_by_privilege_id);
               // return $this->hasOne('Privilege',modified_by_privilege_id);
        }


        //autogenerated this function... 
        public function Professioncode_from_created_by_bunch()
        {
                return $this->hasMany('Professioncode',created_by_professioncode_id);
               // return $this->hasOne('Professioncode',created_by_professioncode_id);
        }


        //autogenerated this function... 
        public function Professioncode_from_modified_by_bunch()
        {
                return $this->hasMany('Professioncode',modified_by_professioncode_id);
               // return $this->hasOne('Professioncode',modified_by_professioncode_id);
        }


        //autogenerated this function... 
        public function ProviderCarrier_from_created_by_bunch()
        {
                return $this->hasMany('ProviderCarrier',created_by_providercarrier_id);
               // return $this->hasOne('ProviderCarrier',created_by_providercarrier_id);
        }


        //autogenerated this function... 
        public function ProviderCarrier_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderCarrier',modified_by_providercarrier_id);
               // return $this->hasOne('ProviderCarrier',modified_by_providercarrier_id);
        }


        //autogenerated this function... 
        public function ProviderCredential_from_created_by_bunch()
        {
                return $this->hasMany('ProviderCredential',created_by_providercredential_id);
               // return $this->hasOne('ProviderCredential',created_by_providercredential_id);
        }


        //autogenerated this function... 
        public function ProviderCredential_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderCredential',modified_by_providercredential_id);
               // return $this->hasOne('ProviderCredential',modified_by_providercredential_id);
        }


        //autogenerated this function... 
        public function ProviderEducation_from_created_by_bunch()
        {
                return $this->hasMany('ProviderEducation',created_by_providereducation_id);
               // return $this->hasOne('ProviderEducation',created_by_providereducation_id);
        }


        //autogenerated this function... 
        public function ProviderEducation_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderEducation',modified_by_providereducation_id);
               // return $this->hasOne('ProviderEducation',modified_by_providereducation_id);
        }


        //autogenerated this function... 
        public function ProviderHospital_from_created_by_bunch()
        {
                return $this->hasMany('ProviderHospital',created_by_providerhospital_id);
               // return $this->hasOne('ProviderHospital',created_by_providerhospital_id);
        }


        //autogenerated this function... 
        public function ProviderHospital_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderHospital',modified_by_providerhospital_id);
               // return $this->hasOne('ProviderHospital',modified_by_providerhospital_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_from_created_by_bunch()
        {
                return $this->hasMany('ProviderLicense',created_by_providerlicense_id);
               // return $this->hasOne('ProviderLicense',created_by_providerlicense_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderLicense',modified_by_providerlicense_id);
               // return $this->hasOne('ProviderLicense',modified_by_providerlicense_id);
        }


        //autogenerated this function... 
        public function ProviderNetwork_from_created_by_bunch()
        {
                return $this->hasMany('ProviderNetwork',created_by_providernetwork_id);
               // return $this->hasOne('ProviderNetwork',created_by_providernetwork_id);
        }


        //autogenerated this function... 
        public function ProviderNetwork_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderNetwork',modified_by_providernetwork_id);
               // return $this->hasOne('ProviderNetwork',modified_by_providernetwork_id);
        }


        //autogenerated this function... 
        public function ProviderReference_from_created_by_bunch()
        {
                return $this->hasMany('ProviderReference',created_by_providerreference_id);
               // return $this->hasOne('ProviderReference',created_by_providerreference_id);
        }


        //autogenerated this function... 
        public function ProviderReference_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderReference',modified_by_providerreference_id);
               // return $this->hasOne('ProviderReference',modified_by_providerreference_id);
        }


        //autogenerated this function... 
        public function ProviderSpeciality_from_created_by_bunch()
        {
                return $this->hasMany('ProviderSpeciality',created_by_providerspeciality_id);
               // return $this->hasOne('ProviderSpeciality',created_by_providerspeciality_id);
        }


        //autogenerated this function... 
        public function ProviderSpeciality_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderSpeciality',modified_by_providerspeciality_id);
               // return $this->hasOne('ProviderSpeciality',modified_by_providerspeciality_id);
        }


        //autogenerated this function... 
        public function ProviderState_from_created_by_bunch()
        {
                return $this->hasMany('ProviderState',created_by_providerstate_id);
               // return $this->hasOne('ProviderState',created_by_providerstate_id);
        }


        //autogenerated this function... 
        public function ProviderState_from_modified_by_bunch()
        {
                return $this->hasMany('ProviderState',modified_by_providerstate_id);
               // return $this->hasOne('ProviderState',modified_by_providerstate_id);
        }


        //autogenerated this function... 
        public function Provider_from_created_by_bunch()
        {
                return $this->hasMany('Provider',created_by_provider_id);
               // return $this->hasOne('Provider',created_by_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_modified_by_bunch()
        {
                return $this->hasMany('Provider',modified_by_provider_id);
               // return $this->hasOne('Provider',modified_by_provider_id);
        }


        //autogenerated this function... 
        public function Servicecode_from_created_by_bunch()
        {
                return $this->hasMany('Servicecode',created_by_servicecode_id);
               // return $this->hasOne('Servicecode',created_by_servicecode_id);
        }


        //autogenerated this function... 
        public function Servicecode_from_modified_by_bunch()
        {
                return $this->hasMany('Servicecode',modified_by_servicecode_id);
               // return $this->hasOne('Servicecode',modified_by_servicecode_id);
        }


        //autogenerated this function... 
        public function Speciality_from_created_by_bunch()
        {
                return $this->hasMany('Speciality',created_by_speciality_id);
               // return $this->hasOne('Speciality',created_by_speciality_id);
        }


        //autogenerated this function... 
        public function Speciality_from_modified_by_bunch()
        {
                return $this->hasMany('Speciality',modified_by_speciality_id);
               // return $this->hasOne('Speciality',modified_by_speciality_id);
        }


        //autogenerated this function... 
        public function TagLink_bunch()
        {
                return $this->hasMany('TagLink',user_id);
               // return $this->hasOne('TagLink',user_id);
        }


	}//the end of class User		
?>