<?php
//Generated by buildORM from the cred:users

	

	class userBase extends BaseORM{ //which extends Eloquent...

		var $table = 'users';

		protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...
		

	}//the end of class user		
?>